AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - 'db/schema.rb'
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 25

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/MethodName:
  EnforcedStyle: snake_case
